'use client'

import { Target, Brain, BarChart3, Sparkles, Globe, Shield } from 'lucide-react'
import { BlurFade } from '@/components/magicui/blur-fade'
import { BorderBeam } from '@/components/magicui/border-beam'

const features = [
  {
    icon: Target,
    title: "Life Wheel Assessment",
    description: "Rate 6 key life areas and get instant insights into your current situation. Visual dashboards show your transformation journey."
  },
  {
    icon: Brain,
    title: "AI-Powered Tasks",
    description: "Get personalized 5-10 minute daily tasks generated by GPT-4 for maximum impact on your weakest areas."
  },
  {
    icon: BarChart3,
    title: "Progress Tracking",
    description: "Real-time visualizations showing your transformation journey with beautiful charts and milestone celebrations."
  },
  {
    icon: Sparkles,
    title: "AI Insights",
    description: "Weekly insights and recommendations based on your progress data to accelerate your transformation."
  },
  {
    icon: Globe,
    title: "Mobile Access",
    description: "Complete tasks on-the-go with our responsive design. Never miss a day of progress building."
  },
  {
    icon: Shield,
    title: "Privacy First",
    description: "End-to-end encryption and GDPR compliant data handling. Your transformation journey stays private."
  }
]

export function Features() {
  return (
    <section id="features" className="py-12 sm:py-16 lg:py-24 bg-muted/50">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <BlurFade delay={0.1} inView>
          <div className="text-center mb-12">
            <h2 className="text-4xl sm:text-5xl font-extrabold leading-tight mb-6">
              Everything you need to{' '}
              <span className="bg-gradient-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent">
                rebuild your life
              </span>
            </h2>
            <p className="text-lg sm:text-xl text-muted-foreground leading-relaxed max-w-3xl mx-auto">
              Stop feeling overwhelmed by change. NoFears breaks down your transformation into 
              manageable daily tasks, tracks your progress, and celebrates every victory.
            </p>
          </div>
        </BlurFade>

        {/* Features Grid */}
        <div className="grid gap-8 md:gap-12 md:grid-cols-2 lg:grid-cols-3">
          {features.map((feature, index) => (
            <BlurFade key={feature.title} delay={0.2 + index * 0.1} inView>
              <div className="bg-background p-8 rounded-2xl border border-border hover:shadow-xl transition-all duration-300 hover:-translate-y-2 relative group">
                <BorderBeam size={250} duration={12} delay={9} />
                
                {/* Icon */}
                <div className="w-16 h-16 rounded-xl bg-gradient-to-br from-primary/20 to-primary/40 flex items-center justify-center mb-6 group-hover:scale-110 transition-transform duration-300">
                  <feature.icon className="w-8 h-8 text-primary" />
                </div>
                
                {/* Content */}
                <h3 className="text-xl font-semibold mb-2">{feature.title}</h3>
                <p className="text-base leading-relaxed text-muted-foreground">{feature.description}</p>
              </div>
            </BlurFade>
          ))}
        </div>

      </div>
    </section>
  )
} 